#!/bin/bash

CP=bin

JARS=`ls lib/`

for JAR in $JARS; do
    CP=$CP:lib/$JAR
done

echo $CP

java -Xms1G -Xmx4G -classpath $CP edu.rpi.tw.eScience.WaterQualityPortal.WebService.WaterAgent > out 2> err &

echo "service started!"
