/*
 green-turtle version 1.1.0 Copyright (c) 2011-2013, R. Alexander Milowski <alex@milowski.com> All rights reserved. */
function URIResolver(){}URIResolver.SCHEME=/^[A-Za-z][A-Za-z0-9\+\-\.]*\:/;
URIResolver.prototype.parseURI=function(a){var b=URIResolver.SCHEME.exec(a);if(!b)throw"Bad URI value, no scheme: "+a;a={spec:a};a.scheme=b[0].substring(0,b[0].length-1);a.schemeSpecificPart=a.spec.substring(b[0].length);"/"==a.schemeSpecificPart.charAt(0)&&"/"==a.schemeSpecificPart.charAt(1)?this.parseGeneric(a):a.isGeneric=!1;a.normalize=function(){if(this.isGeneric&&0!=this.segments.length){if(1<this.path.length&&"/."==this.path.substring(this.path.length-2))this.path=this.path.substring(0,this.path.length-
1),this.segments.splice(this.segments.length-1,1);else{var a=this.path.charAt(this.path.length-1);"/"!=a&&(a="");for(var b=0;b<this.segments.length;b++)0<b&&".."==this.segments[b]&&(this.segments.splice(b-1,2),b-=2),"."==this.segments[b]&&(this.segments.splice(b,1),b--);this.path=0==this.segments.length?"/":"/"+this.segments.join("/")+a}this.schemeSpecificPart="//"+this.authority+this.path;"undefined"!=typeof this.query&&(this.schemeSpecificPart+="?"+this.query);"undefined"!=typeof this.fragment&&
(this.schemeSpecificPart+="#"+this.fragment);this.spec=this.scheme+":"+this.schemeSpecificPart}};a.resolve=function(a){if(!a)return this.spec;if("#"==a.charAt(0)){var b=this.spec.lastIndexOf("#");return 0>b?this.spec+a:this.spec.substring(0,b)+a}if(!this.isGeneric)throw"Cannot resolve uri against non-generic URI: "+this.spec;a.indexOf(":");if("/"==a.charAt(0))return this.scheme+"://"+this.authority+a;if("."==a.charAt(0)&&"/"==a.charAt(1)){if("/"==this.path.charAt(this.path.length-1))return this.scheme+
"://"+this.authority+this.path+a.substring(2);b=this.path.lastIndexOf("/");return this.scheme+"://"+this.authority+this.path.substring(0,b)+a.substring(1)}if(URIResolver.SCHEME.test(a))return a;if("?"==a.charAt(0)||"/"==this.path.charAt(this.path.length-1))return this.scheme+"://"+this.authority+this.path+a;b=this.path.lastIndexOf("/");return this.scheme+"://"+this.authority+this.path.substring(0,b+1)+a};a.relativeTo=function(a){if(a.scheme!=this.scheme)return this.spec;if(!this.isGeneric)throw"A non generic URI cannot be made relative: "+
this.spec;if(!a.isGeneric)throw"Cannot make a relative URI against a non-generic URI: "+a.spec;if(a.authority!=this.authority)return this.spec;for(var b=0;b<this.segments.length&&b<a.segments.length;b++)if(this.segments[b]!=a.segments[b]){for(var d="",i=b;i<a.segments.length;i++)d+="../";for(i=b;i<this.segments.length;i++)d+=this.segments[i],i+1<this.segments.length&&(d+="/");"/"==this.path.charAt(this.path.length-1)&&(d+="/");return d}if(this.segments.length==a.segments.length)return this.hash?this.hash:
this.query?this.query:"";if(b<this.segments.length){d="";for(i=b;i<this.segments.length;i++)d+=this.segments[i],i+1<this.segments.length&&(d+="/");"/"==this.path.charAt(this.path.length-1)&&(d+="/");return d}throw"Cannot calculate a relative URI for "+this.spec+" against "+a.spec;};return a};
URIResolver.prototype.parseGeneric=function(a){if("/"!=a.schemeSpecificPart.charAt(0)||"/"!=a.schemeSpecificPart.charAt(1))throw"Generic URI values should start with '//':"+a.spec;var b=a.schemeSpecificPart.substring(2),c=b.indexOf("/");a.authority=0>c?b:b.substring(0,c);a.path=0>c?"":b.substring(c);b=a.path.indexOf("#");0<=b&&(a.fragment=a.path.substring(b+1),a.path=a.path.substring(0,b));b=a.path.indexOf("?");0<=b&&(a.query=a.path.substring(b+1),a.path=a.path.substring(0,b));if("/"==a.path||""==
a.path)a.segments=[];else{a.segments=a.path.split(/\//);0<a.segments.length&&(""==a.segments[0]&&1<a.path.length&&"/"!=a.path.charAt(1))&&a.segments.shift();0<a.segments.length&&0<a.path.length&&"/"==a.path.charAt(a.path.length-1)&&""==a.segments[a.segments.length-1]&&1<a.path.length&&"/"!=a.path.charAt(a.path.length-2)&&a.segments.pop();for(b=0;b<a.segments.length;b++)for(var c=a.segments[b].split(/%[A-Za-z0-9][A-Za-z0-9]|[\ud800-\udfff][\ud800-\udfff]|[A-Za-z0-9\-\._~!$&'()*+,;=@:\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+/),
f=0;f<c.length;f++)if(0<c[f].length)throw"Unecaped character "+c[f].charAt(0)+" ("+c[f].charCodeAt(0)+") in URI "+a.spec;}a.isGeneric=!0};RDFaProcessor.prototype=new URIResolver;RDFaProcessor.prototype.constructor=RDFaProcessor;
function RDFaProcessor(a){this.target=a?a:{graph:{subjects:{},prefixes:{},terms:{}}};this.theOne="_:"+(new Date).getTime();this.vocabulary=this.language=null;this.blankCounter=0;this.langAttributes=[{namespaceURI:"http://www.w3.org/XML/1998/namespace",localName:"lang"}];this.inXHTMLMode=!1;this.absURIRE=/[\w\_\-]+:\S+/;this.finishedHandlers=[];this.init()}RDFaProcessor.prototype.newBlankNode=function(){this.blankCounter++;return"_:"+this.blankCounter};RDFaProcessor.XMLLiteralURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral";
RDFaProcessor.HTMLLiteralURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML";RDFaProcessor.PlainLiteralURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral";RDFaProcessor.objectURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#object";RDFaProcessor.typeURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#type";RDFaProcessor.nameChar="[-A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\u10000-\uefffF.0-9\u00b7\u0300-\u036f\u203f-\u2040]";
RDFaProcessor.nameStartChar="[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u0131\u0134-\u013e\u0141-\u0148\u014a-\u017e\u0180-\u01c3\u01cd-\u01f0\u01f4-\u01f5\u01fa-\u0217\u0250-\u02a8\u02bb-\u02c1\u0386\u0388-\u038a\u038c\u038e-\u03a1\u03a3-\u03ce\u03d0-\u03d6\u03da\u03dc\u03de\u03e0\u03e2-\u03f3\u0401-\u040c\u040e-\u044f\u0451-\u045c\u045e-\u0481\u0490-\u04c4\u04c7-\u04c8\u04cb-\u04cc\u04d0-\u04eb\u04ee-\u04f5\u04f8-\u04f9\u0531-\u0556\u0559\u0561-\u0586\u05d0-\u05ea\u05f0-\u05f2\u0621-\u063a\u0641-\u064a\u0671-\u06b7\u06ba-\u06be\u06c0-\u06ce\u06d0-\u06d3\u06d5\u06e5-\u06e6\u0905-\u0939\u093d\u0958-\u0961\u0985-\u098c\u098f-\u0990\u0993-\u09a8\u09aa-\u09b0\u09b2\u09b6-\u09b9\u09dc-\u09dd\u09df-\u09e1\u09f0-\u09f1\u0a05-\u0a0a\u0a0f-\u0a10\u0a13-\u0a28\u0a2a-\u0a30\u0a32-\u0a33\u0a35-\u0a36\u0a38-\u0a39\u0a59-\u0a5c\u0a5e\u0a72-\u0a74\u0a85-\u0a8b\u0a8d\u0a8f-\u0a91\u0a93-\u0aa8\u0aaa-\u0ab0\u0ab2-\u0ab3\u0ab5-\u0ab9\u0abd\u0ae0\u0b05-\u0b0c\u0b0f-\u0b10\u0b13-\u0b28\u0b2a-\u0b30\u0b32-\u0b33\u0b36-\u0b39\u0b3d\u0b5c-\u0b5d\u0b5f-\u0b61\u0b85-\u0b8a\u0b8e-\u0b90\u0b92-\u0b95\u0b99-\u0b9a\u0b9c\u0b9e-\u0b9f\u0ba3-\u0ba4\u0ba8-\u0baa\u0bae-\u0bb5\u0bb7-\u0bb9\u0c05-\u0c0c\u0c0e-\u0c10\u0c12-\u0c28\u0c2a-\u0c33\u0c35-\u0c39\u0c60-\u0c61\u0c85-\u0c8c\u0c8e-\u0c90\u0c92-\u0ca8\u0caa-\u0cb3\u0cb5-\u0cb9\u0cde\u0ce0-\u0ce1\u0d05-\u0d0c\u0d0e-\u0d10\u0d12-\u0d28\u0d2a-\u0d39\u0d60-\u0d61\u0e01-\u0e2e\u0e30\u0e32-\u0e33\u0e40-\u0e45\u0e81-\u0e82\u0e84\u0e87-\u0e88\u0e8a\u0e8d\u0e94-\u0e97\u0e99-\u0e9f\u0ea1-\u0ea3\u0ea5\u0ea7\u0eaa-\u0eab\u0ead-\u0eae\u0eb0\u0eb2-\u0eb3\u0ebd\u0ec0-\u0ec4\u0f40-\u0f47\u0f49-\u0f69\u10a0-\u10c5\u10d0-\u10f6\u1100\u1102-\u1103\u1105-\u1107\u1109\u110b-\u110c\u110e-\u1112\u113c\u113e\u1140\u114c\u114e\u1150\u1154-\u1155\u1159\u115f-\u1161\u1163\u1165\u1167\u1169\u116d-\u116e\u1172-\u1173\u1175\u119e\u11a8\u11ab\u11ae-\u11af\u11b7-\u11b8\u11ba\u11bc-\u11c2\u11eb\u11f0\u11f9\u1e00-\u1e9b\u1ea0-\u1ef9\u1f00-\u1f15\u1f18-\u1f1d\u1f20-\u1f45\u1f48-\u1f4d\u1f50-\u1f57\u1f59\u1f5b\u1f5d\u1f5f-\u1f7d\u1f80-\u1fb4\u1fb6-\u1fbc\u1fbe\u1fc2-\u1fc4\u1fc6-\u1fcc\u1fd0-\u1fd3\u1fd6-\u1fdb\u1fe0-\u1fec\u1ff2-\u1ff4\u1ff6-\u1ffc\u2126\u212a-\u212b\u212e\u2180-\u2182\u3041-\u3094\u30a1-\u30fa\u3105-\u312c\uac00-\ud7a3\u4e00-\u9fa5\u3007\u3021-\u3029_]";
RDFaProcessor.NCNAME=RegExp("^"+RDFaProcessor.nameStartChar+RDFaProcessor.nameChar+"*$");RDFaProcessor.trim=function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};RDFaProcessor.prototype.tokenize=function(a){return RDFaProcessor.trim(a).split(/\s+/)};
RDFaProcessor.prototype.parseSafeCURIEOrCURIEOrURI=function(a,b,c){a=RDFaProcessor.trim(a);return"["==a.charAt(0)&&"]"==a.charAt(a.length-1)?(a=a.substring(1,a.length-1),a=a.trim(a),0==a.length?null:"_:"==a?this.theOne:this.parseCURIE(a,b,c)):this.parseCURIEOrURI(a,b,c)};
RDFaProcessor.prototype.parseCURIE=function(a,b){var c=a.indexOf(":");if(0<=c){var f=a.substring(0,c);if(""==f)return(f=b[""])?f+a.substring(c+1):null;if("_"==f)return"_:"+a.substring(c+1);if(RDFaProcessor.NCNAME.test(f)&&(f=b[f]))return f+a.substring(c+1)}return null};RDFaProcessor.prototype.parseCURIEOrURI=function(a,b,c){return(b=this.parseCURIE(a,b,c))?b:this.resolveAndNormalize(c,a)};
RDFaProcessor.prototype.parsePredicate=function(a,b,c,f,d,i){return""==a?null:(a=this.parseTermOrCURIEOrAbsURI(a,b,i?null:c,f,d))&&0==a.indexOf("_:")?null:a};RDFaProcessor.prototype.parseTermOrCURIEOrURI=function(a,b,c,f,d){a=RDFaProcessor.trim(a);if((f=this.parseCURIE(a,f,d))||(f=c[a]))return f;f=a.toLowerCase();return(f=c[f])?f:b&&!this.absURIRE.exec(a)?b+a:this.resolveAndNormalize(d,a)};
RDFaProcessor.prototype.parseTermOrCURIEOrAbsURI=function(a,b,c,f,d){a=RDFaProcessor.trim(a);if(f=this.parseCURIE(a,f,d))return f;if(c){if(b&&!this.absURIRE.exec(a))return b+a;if(b=c[a])return b;b=a.toLowerCase();if(b=c[b])return b}return this.absURIRE.exec(a)?this.resolveAndNormalize(d,a):null};RDFaProcessor.prototype.resolveAndNormalize=function(a,b){var c=a.resolve(b),c=this.parseURI(c);c.normalize();return c.spec};
RDFaProcessor.prototype.parsePrefixMappings=function(a,b){for(var c=this.tokenize(a),f=null,d=0;d<c.length;d++)":"==c[d][c[d].length-1]?f=c[d].substring(0,c[d].length-1):f&&(b[f]=this.target.baseURI?this.target.baseURI.resolve(c[d]):c[d],f=null)};RDFaProcessor.prototype.copyMappings=function(a){var b={},c;for(c in a)b[c]=a[c];return b};RDFaProcessor.prototype.ancestorPath=function(a){for(var b="";a&&a.nodeType!=Node.DOCUMENT_NODE;)b="/"+a.localName+b,a=a.parentNode;return b};
RDFaProcessor.prototype.setContext=function(a){"html"==a.localName&&"XHTML+RDFa 1.1"==a.getAttribute("version")?this.setXHTMLContext():"html"==a.localName||"http://www.w3.org/1999/xhtml"==a.namespaceURI?document.doctype?"-//W3C//DTD XHTML+RDFa 1.0//EN"==document.doctype.publicId&&"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd"==document.doctype.systemId?(console.log("WARNING: RDF 1.0 is not supported.  Defaulting to HTML5 mode."),this.setHTMLContext()):"-//W3C//DTD XHTML+RDFa 1.1//EN"==document.doctype.publicId&&
"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-2.dtd"==document.doctype.systemId?this.setXHTMLContext():this.setHTMLContext():this.setHTMLContext():this.setXMLContext()};
RDFaProcessor.prototype.setInitialContext=function(){this.vocabulary=null;this.target.graph.prefixes={};this.target.graph.terms={};this.langAttributes=[{namespaceURI:"http://www.w3.org/XML/1998/namespace",localName:"lang"}];this.target.graph.prefixes[""]="http://www.w3.org/1999/xhtml/vocab#";this.target.graph.prefixes.grddl="http://www.w3.org/2003/g/data-view#";this.target.graph.prefixes.ma="http://www.w3.org/ns/ma-ont#";this.target.graph.prefixes.owl="http://www.w3.org/2002/07/owl#";this.target.graph.prefixes.rdf=
"http://www.w3.org/1999/02/22-rdf-syntax-ns#";this.target.graph.prefixes.rdfa="http://www.w3.org/ns/rdfa#";this.target.graph.prefixes.rdfs="http://www.w3.org/2000/01/rdf-schema#";this.target.graph.prefixes.rif="http://www.w3.org/2007/rif#";this.target.graph.prefixes.skos="http://www.w3.org/2004/02/skos/core#";this.target.graph.prefixes.skosxl="http://www.w3.org/2008/05/skos-xl#";this.target.graph.prefixes.wdr="http://www.w3.org/2007/05/powder#";this.target.graph.prefixes["void"]="http://rdfs.org/ns/void#";
this.target.graph.prefixes.wdrs="http://www.w3.org/2007/05/powder-s#";this.target.graph.prefixes.xhv="http://www.w3.org/1999/xhtml/vocab#";this.target.graph.prefixes.xml="http://www.w3.org/XML/1998/namespace";this.target.graph.prefixes.xsd="http://www.w3.org/2001/XMLSchema#";this.target.graph.prefixes.sd="http://www.w3.org/ns/sparql-service-description#";this.target.graph.prefixes.org="http://www.w3.org/ns/org#";this.target.graph.prefixes.gldp="http://www.w3.org/ns/people#";this.target.graph.prefixes.cnt=
"http://www.w3.org/2008/content#";this.target.graph.prefixes.dcat="http://www.w3.org/ns/dcat#";this.target.graph.prefixes.earl="http://www.w3.org/ns/earl#";this.target.graph.prefixes.ht="http://www.w3.org/2006/http#";this.target.graph.prefixes.ptr="http://www.w3.org/2009/pointers#";this.target.graph.prefixes.cc="http://creativecommons.org/ns#";this.target.graph.prefixes.ctag="http://commontag.org/ns#";this.target.graph.prefixes.dc="http://purl.org/dc/terms/";this.target.graph.prefixes.dcterms="http://purl.org/dc/terms/";
this.target.graph.prefixes.foaf="http://xmlns.com/foaf/0.1/";this.target.graph.prefixes.gr="http://purl.org/goodrelations/v1#";this.target.graph.prefixes.ical="http://www.w3.org/2002/12/cal/icaltzd#";this.target.graph.prefixes.og="http://ogp.me/ns#";this.target.graph.prefixes.rev="http://purl.org/stuff/rev#";this.target.graph.prefixes.sioc="http://rdfs.org/sioc/ns#";this.target.graph.prefixes.v="http://rdf.data-vocabulary.org/#";this.target.graph.prefixes.vcard="http://www.w3.org/2006/vcard/ns#";
this.target.graph.prefixes.schema="http://schema.org/";this.target.graph.terms.describedby="http://www.w3.org/2007/05/powder-s#describedby";this.target.graph.terms.license="http://www.w3.org/1999/xhtml/vocab#license";this.target.graph.terms.role="http://www.w3.org/1999/xhtml/vocab#role"};RDFaProcessor.prototype.setXMLContext=function(){this.setInitialContext();this.inHTMLMode=this.inXHTMLMode=!1};
RDFaProcessor.prototype.setHTMLContext=function(){this.setInitialContext();this.langAttributes=[{namespaceURI:"http://www.w3.org/XML/1998/namespace",localName:"lang"},{namespaceURI:null,localName:"lang"}];this.inXHTMLMode=!1;this.inHTMLMode=!0};
RDFaProcessor.prototype.setXHTMLContext=function(){this.setInitialContext();this.inXHTMLMode=!0;this.inHTMLMode=!1;this.langAttributes=[{namespaceURI:"http://www.w3.org/XML/1998/namespace",localName:"lang"},{namespaceURI:null,localName:"lang"}];this.target.graph.terms.alternate="http://www.w3.org/1999/xhtml/vocab#alternate";this.target.graph.terms.appendix="http://www.w3.org/1999/xhtml/vocab#appendix";this.target.graph.terms.bookmark="http://www.w3.org/1999/xhtml/vocab#bookmark";this.target.graph.terms.cite=
"http://www.w3.org/1999/xhtml/vocab#cite";this.target.graph.terms.chapter="http://www.w3.org/1999/xhtml/vocab#chapter";this.target.graph.terms.contents="http://www.w3.org/1999/xhtml/vocab#contents";this.target.graph.terms.copyright="http://www.w3.org/1999/xhtml/vocab#copyright";this.target.graph.terms.first="http://www.w3.org/1999/xhtml/vocab#first";this.target.graph.terms.glossary="http://www.w3.org/1999/xhtml/vocab#glossary";this.target.graph.terms.help="http://www.w3.org/1999/xhtml/vocab#help";
this.target.graph.terms.icon="http://www.w3.org/1999/xhtml/vocab#icon";this.target.graph.terms.index="http://www.w3.org/1999/xhtml/vocab#index";this.target.graph.terms.last="http://www.w3.org/1999/xhtml/vocab#last";this.target.graph.terms.license="http://www.w3.org/1999/xhtml/vocab#license";this.target.graph.terms.meta="http://www.w3.org/1999/xhtml/vocab#meta";this.target.graph.terms.next="http://www.w3.org/1999/xhtml/vocab#next";this.target.graph.terms.prev="http://www.w3.org/1999/xhtml/vocab#prev";
this.target.graph.terms.previous="http://www.w3.org/1999/xhtml/vocab#previous";this.target.graph.terms.section="http://www.w3.org/1999/xhtml/vocab#section";this.target.graph.terms.stylesheet="http://www.w3.org/1999/xhtml/vocab#stylesheet";this.target.graph.terms.subsection="http://www.w3.org/1999/xhtml/vocab#subsection";this.target.graph.terms.start="http://www.w3.org/1999/xhtml/vocab#start";this.target.graph.terms.top="http://www.w3.org/1999/xhtml/vocab#top";this.target.graph.terms.up="http://www.w3.org/1999/xhtml/vocab#up";
this.target.graph.terms.p3pv1="http://www.w3.org/1999/xhtml/vocab#p3pv1";this.target.graph.terms.related="http://www.w3.org/1999/xhtml/vocab#related";this.target.graph.terms.role="http://www.w3.org/1999/xhtml/vocab#role";this.target.graph.terms.transformation="http://www.w3.org/1999/xhtml/vocab#transformation"};RDFaProcessor.prototype.init=function(){};RDFaProcessor.prototype.newSubjectOrigin=function(){};RDFaProcessor.prototype.addTriple=function(){};
RDFaProcessor.dateTimeTypes=[{pattern:/-?P(?:[0-9]+Y)?(?:[0-9]+M)?(?:[0-9]+D)?(?:T(?:[0-9]+H)?(?:[0-9]+M)?(?:[0-9]+(?:\.[0-9]+)?S)?)?/,type:"http://www.w3.org/2001/XMLSchema#duration"},{pattern:/-?(?:[1-9][0-9][0-9][0-9]|0[1-9][0-9][0-9]|00[1-9][0-9]|000[1-9])-[0-9][0-9]-[0-9][0-9]T(?:[0-1][0-9]|2[0-4]):[0-5][0-9]:[0-5][0-9](?:\.[0-9]+)?(?:Z|[+\-][0-9][0-9]:[0-9][0-9])?/,type:"http://www.w3.org/2001/XMLSchema#dateTime"},{pattern:/-?(?:[1-9][0-9][0-9][0-9]|0[1-9][0-9][0-9]|00[1-9][0-9]|000[1-9])-[0-9][0-9]-[0-9][0-9](?:Z|[+\-][0-9][0-9]:[0-9][0-9])?/,
type:"http://www.w3.org/2001/XMLSchema#date"},{pattern:/(?:[0-1][0-9]|2[0-4]):[0-5][0-9]:[0-5][0-9](?:\.[0-9]+)?(?:Z|[+\-][0-9][0-9]:[0-9][0-9])?/,type:"http://www.w3.org/2001/XMLSchema#time"},{pattern:/-?(?:[1-9][0-9][0-9][0-9]|0[1-9][0-9][0-9]|00[1-9][0-9]|000[1-9])-[0-9][0-9]/,type:"http://www.w3.org/2001/XMLSchema#gYearMonth"},{pattern:/-?[1-9][0-9][0-9][0-9]|0[1-9][0-9][0-9]|00[1-9][0-9]|000[1-9]/,type:"http://www.w3.org/2001/XMLSchema#gYear"}];
RDFaProcessor.deriveDateTimeType=function(a){for(var b=0;b<RDFaProcessor.dateTimeTypes.length;b++){var c=RDFaProcessor.dateTimeTypes[b].pattern.exec(a);if(c&&c[0].length==a.length)return RDFaProcessor.dateTimeTypes[b].type}return null};
RDFaProcessor.prototype.process=function(a,b){a.nodeType==Node.DOCUMENT_NODE?(a=a.documentElement,this.setContext(a)):a.parentNode.nodeType==Node.DOCUMENT_NODE&&this.setContext(a);var c=[],f=function(a){var c=a.indexOf("#");0<=c&&(a=a.substring(0,c));b&&b.baseURIMap&&(a=b.baseURIMap(a));return a};for(c.push({current:a,context:this.push(null,f(a.baseURI))});0<c.length;){var d=c.shift();if(d.parent){if(!(d.context.parent&&d.context.parent.listMapping==d.listMapping))for(var i in d.listMapping){var j=
d.listMapping[i];if(0==j.length)this.addTriple(d.parent,d.subject,i,{type:RDFaProcessor.objectURI,value:"http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"});else{for(var g=[],e=0;e<j.length;e++)g.push(this.newBlankNode());for(e=0;e<g.length;e++)this.addTriple(d.parent,g[e],"http://www.w3.org/1999/02/22-rdf-syntax-ns#first",j[e]),this.addTriple(d.parent,g[e],"http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",{type:RDFaProcessor.objectURI,value:e+1<g.length?g[e+1]:"http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"});
this.addTriple(d.parent,d.subject,i,{type:RDFaProcessor.objectURI,value:g[0]})}}}else{var g=d.current,d=d.context,x=!1,h=null,m=null,l=null,q=d.prefixes,j=!1,G=[],y=d.listMapping,J=d.parent?!1:!0,F=d.language,A=d.vocabulary,n=this.parseURI(f(g.baseURI));g.item=null;if(e=g.getAttributeNode("vocab"))e=RDFaProcessor.trim(e.value),0<e.length?(A=e,this.addTriple(g,n.spec,"http://www.w3.org/ns/rdfa#usesVocabulary",{type:RDFaProcessor.objectURI,value:A})):A=this.vocabulary;for(e=0;e<g.attributes.length;e++){var r=
g.attributes[e];if("x"==r.nodeName.charAt(0)&&0==r.nodeName.indexOf("xmlns:")){j||(q=this.copyMappings(q),j=!0);var t=r.nodeName.substring(6),r=RDFaProcessor.trim(r.value);q[t]=this.target.baseURI?this.target.baseURI.resolve(r):r}}if(e=g.getAttributeNode("prefix"))j||(q=this.copyMappings(q),j=!0),this.parsePrefixMappings(e.value,q);j=null;for(e=0;!j&&e<this.langAttributes.length;e++)j=g.getAttributeNodeNS(this.langAttributes[e].namespaceURI,this.langAttributes[e].localName);j&&(e=RDFaProcessor.trim(j.value),
F=0<e.length?e:null);var t=g.getAttributeNode("rel"),r=g.getAttributeNode("rev"),u=g.getAttributeNode("typeof"),D=g.getAttributeNode("property"),H=g.getAttributeNode("datatype"),I=this.inHTMLMode?g.getAttributeNode("datetime"):null,E=g.getAttributeNode("content"),v=g.getAttributeNode("about"),B=g.getAttributeNode("src"),z=g.getAttributeNode("resource"),C=g.getAttributeNode("href"),K=g.getAttributeNode("inlist"),k=[];if(t)for(var w=this.tokenize(t.value),e=0;e<w.length;e++)(i=this.parsePredicate(w[e],
A,d.terms,q,n,this.inHTMLMode&&null!=D))&&k.push(i);var p=[];if(r){w=this.tokenize(r.value);for(e=0;e<w.length;e++)(i=this.parsePredicate(w[e],A,d.terms,q,n,this.inHTMLMode&&null!=D))&&p.push(i)}if(this.inHTMLMode&&(null!=t||null!=r)&&null!=D)0==k.length&&(t=null),0==p.length&&(r=null);if(t||r){v&&(h=this.parseSafeCURIEOrCURIEOrURI(v.value,q,n));u&&(l=h);h||(g.parentNode.nodeType==Node.DOCUMENT_NODE?h=f(g.baseURI):d.parentObject&&(h=f(g.parentNode.baseURI)==d.parentObject?f(g.baseURI):d.parentObject));
z&&(m=this.parseSafeCURIEOrCURIEOrURI(z.value,q,n));if(!m)if(C)m=this.resolveAndNormalize(n,encodeURI(C.value));else if(B)m=this.resolveAndNormalize(n,encodeURI(B.value));else if(u&&!v&&(!this.inXHTMLMode||!("head"==g.localName||"body"==g.localName)))m=this.newBlankNode();u&&!v&&this.inXHTMLMode&&("head"==g.localName||"body"==g.localName)?l=h:u&&!v&&(l=m)}else if(D&&!E&&!H){if(v&&(h=this.parseSafeCURIEOrCURIEOrURI(v.value,q,n),u&&(l=h)),!h&&g.parentNode.nodeType==Node.DOCUMENT_NODE?(h=f(g.baseURI),
u&&(l=h)):!h&&d.parentObject&&(h=f(g.parentNode.baseURI)==d.parentObject?f(g.baseURI):d.parentObject),u&&!l){z&&(l=this.parseSafeCURIEOrCURIEOrURI(z.value,q,n));!l&&C&&(l=this.resolveAndNormalize(n,encodeURI(C.value)));!l&&B&&(l=this.resolveAndNormalize(n,encodeURI(B.value)));if(!l&&(this.inXHTMLMode||this.inHTMLMode)&&("head"==g.localName||"body"==g.localName))l=h;l||(l=this.newBlankNode());m=l}}else v&&(h=this.parseSafeCURIEOrCURIEOrURI(v.value,q,n)),!h&&z&&(h=this.parseSafeCURIEOrCURIEOrURI(z.value,
q,n)),!h&&C&&(h=this.resolveAndNormalize(n,encodeURI(C.value))),!h&&B&&(h=this.resolveAndNormalize(n,encodeURI(B.value))),h||(g.parentNode.nodeType==Node.DOCUMENT_NODE?h=f(g.baseURI):(this.inXHTMLMode||this.inHTMLMode)&&("head"==g.localName||"body"==g.localName)?h=f(g.parentNode.baseURI)==d.parentObject?f(g.baseURI):d.parentObject:u?h=this.newBlankNode():d.parentObject&&(h=f(g.parentNode.baseURI)==d.parentObject?f(g.baseURI):d.parentObject,D||(x=!0))),u&&(l=h);if(h&&(v||z||l))e=h,u&&(!v&&!z&&m)&&
(e=m),this.newSubjectOrigin(g,e);if(l){w=this.tokenize(u.value);for(e=0;e<w.length;e++)(j=this.parseTermOrCURIEOrAbsURI(w[e],A,d.terms,q,n))&&this.addTriple(g,l,RDFaProcessor.typeURI,{type:RDFaProcessor.objectURI,value:j})}h&&h!=d.parentObject&&(y={},J=!0);if(m){if(t&&K)for(e=0;e<k.length;e++)j=y[k[e]],j||(j=[],y[k[e]]=j),j.push({type:RDFaProcessor.objectURI,value:m});else if(t)for(e=0;e<k.length;e++)this.addTriple(g,h,k[e],{type:RDFaProcessor.objectURI,value:m});if(r)for(e=0;e<p.length;e++)this.addTriple(g,
m,p[e],{type:RDFaProcessor.objectURI,value:h})}else{if(h&&!m&&(t||r))m=this.newBlankNode();if(t&&K)for(e=0;e<k.length;e++)j=y[k[e]],j||(j=[],y[i]=j),G.push({predicate:k[e],list:j});else if(t)for(e=0;e<k.length;e++)G.push({predicate:k[e],forward:!0});if(r)for(e=0;e<p.length;e++)G.push({predicate:p[e],forward:!1})}if(D){p=k=null;H?(k=""==H.value?RDFaProcessor.PlainLiteralURI:this.parseTermOrCURIEOrAbsURI(H.value,A,d.terms,q,n),p=I&&!E?I.value:k==RDFaProcessor.XMLLiteralURI||k==RDFaProcessor.HTMLLiteralURI?
null:E?E.value:g.textContent):E?(k=RDFaProcessor.PlainLiteralURI,p=E.value):I?(p=I.value,k=RDFaProcessor.deriveDateTimeType(p),k||(k=RDFaProcessor.PlainLiteralURI)):!t&&!r&&(z&&(p=this.parseSafeCURIEOrCURIEOrURI(z.value,q,n)),!p&&C?p=this.resolveAndNormalize(n,encodeURI(C.value)):!p&&B&&(p=this.resolveAndNormalize(n,encodeURI(B.value))),p&&(k=RDFaProcessor.objectURI));k||(u&&!v?(k=RDFaProcessor.objectURI,p=l):(p=g.textContent,this.inHTMLMode&&"time"==g.localName&&(k=RDFaProcessor.deriveDateTimeType(p)),
k||(k=RDFaProcessor.PlainLiteralURI)));w=this.tokenize(D.value);for(e=0;e<w.length;e++)if(i=this.parsePredicate(w[e],A,d.terms,q,n))K?(j=y[i],j||(j=[],y[i]=j),j.push(k==RDFaProcessor.XMLLiteralURI||k==RDFaProcessor.HTMLLiteralURI?{type:k,value:g.childNodes}:{type:k?k:RDFaProcessor.PlainLiteralURI,value:p,language:F})):k==RDFaProcessor.XMLLiteralURI||k==RDFaProcessor.HTMLLiteralURI?this.addTriple(g,h,i,{type:k,value:g.childNodes}):this.addTriple(g,h,i,{type:k?k:RDFaProcessor.PlainLiteralURI,value:p,
language:F})}if(h&&!x)for(e=0;e<d.incomplete.length;e++)d.incomplete[e].list?d.incomplete[e].list.push({type:RDFaProcessor.objectURI,value:h}):d.incomplete[e].forward?this.addTriple(g,d.subject,d.incomplete[e].predicate,{type:RDFaProcessor.objectURI,value:h}):this.addTriple(g,h,d.incomplete[e].predicate,{type:RDFaProcessor.objectURI,value:d.subject});l=null;n=h;x?(l=this.push(d,d.subject),l.parentObject=f(g.parentNode.baseURI)==d.parentObject?f(g.baseURI):d.parentObject,l.incomplete=d.incomplete,
l.language=F,l.prefixes=q):(l=this.push(d,h),l.parentObject=m?m:h?h:d.subject,l.prefixes=q,l.incomplete=G,m&&(n=m,y={},J=!0),l.listMapping=y,l.language=F);l.vocabulary=A;J&&c.unshift({parent:g,context:d,subject:n,listMapping:y});for(g=g.lastChild;g;g=g.previousSibling)g.nodeType==Node.ELEMENT_NODE&&c.unshift({current:g,context:l})}}this.inHTMLMode&&this.copyProperties();for(e=0;e<this.finishedHandlers.length;e++)this.finishedHandlers[e](a)};RDFaProcessor.prototype.copyProperties=function(){};
RDFaProcessor.prototype.push=function(a,b){return{parent:a,subject:b?b:a?a.subject:null,parentObject:null,incomplete:[],listMapping:a?a.listMapping:{},language:a?a.language:this.language,prefixes:a?a.prefixes:this.target.graph.prefixes,terms:a?a.terms:this.target.graph.terms,vocabulary:a?a.vocabulary:this.vocabulary}};
function RDFaGraph(){var a=this;this.curieParser={trim:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},parse:function(b,c){b=this.trim(b);"["==b.charAt(0)&&"]"==b.charAt(b.length-1)&&(b=b.substring(1,b.length-1));var f=b.indexOf(":");if(0<=f){var d=b.substring(0,f);if(""==d)return(d=a.prefixes[""])?d+b.substring(f+1):null;if("_"==d)return"_:"+b.substring(f+1);if(DocumentData.NCNAME.test(d)&&(d=a.prefixes[d]))return d+b.substring(f+1)}return c?a.baseURI.resolve(b):b}};this.base=null;
this.toString=function(a){var c=a.shorten?{graph:this,shorten:!0,prefixesUsed:{}}:null;s="";for(var f in this.subjects)s+=this.subjects[f].toString(c),s+="\n";a=a.baseURI?"@base <"+baseURI+"> .\n":"";if(c.shorten)for(var d in c.prefixesUsed)a+="@prefix "+d+" <"+this.prefixes[d]+"> .\n";return 0==a.length?s:a+"\n"+s};this.clear=function(){this.subjects={};this.prefixes={};this.terms={}};this.clear()}RDFaGraph.prototype.expand=function(a){return this.curieParser.parse(a,!0)};
RDFaGraph.prototype.shorten=function(a,b){for(prefix in this.prefixes){console.log("Testing "+prefix+" against "+a);var c=this.prefixes[prefix];if(0==a.indexOf(c))return b&&(b[prefix]=c),prefix+":"+a.substring(c.length)}return null};function RDFaSubject(a,b){this.graph=a;this.id=this.subject=b;this.predicates={};this.origins=[];this.types=[]}
RDFaSubject.prototype.toString=function(a){var b=null;"_:"==this.subject.substring(0,2)?b=this.subject:a&&a.shorten?(b=this.graph.shorten(this.subject,a.prefixesUsed))||(b="<"+this.subject+">"):b="<"+this.subject+">";var c=!0,f;for(f in this.predicates)c?c=!1:b+=";\n",b+=" "+this.predicates[f].toString(a);return b+" ."};
RDFaSubject.prototype.toObject=function(){var a={subject:this.subject,predicates:{}},b;for(b in this.predicates){var c=this.predicates[b],f={predicate:b,objects:[]};a.predicates[b]=f;for(var d=0;d<c.objects.length;d++){var i=c.objects[d];if(i.type==RDFaProcessor.XMLLiteralURI){for(var j=new XMLSerializer,g="",e=0;e<i.value.length;e++)i.value[e].nodeType==Node.ELEMENT_NODE?g+=j.serializeToString(i.value[e]):i.value[e].nodeType==Node.TEXT_NODE&&(g+=i.value[e].nodeValue);f.objects.push({type:i.type,
value:g,language:i.language})}else f.objects.push({type:i.type,value:i.value,language:i.language})}}return a};RDFaSubject.prototype.getValues=function(){for(var a=[],b=0;b<arguments.length;b++){var c=this.graph.curieParser.parse(arguments[b],!0);if(c=this.predicates[c])for(var f=0;f<c.objects.length;f++)a.push(c.objects[f].value)}return a};function RDFaPredicate(a){this.predicate=this.id=a;this.objects=[]}
RDFaPredicate.getPrefixMap=function(a){for(var b={};a.attributes;){for(var c=0;c<a.attributes.length;c++)if("http://www.w3.org/2000/xmlns/"==a.attributes[c].namespaceURI){var f=a.attributes[c].localName;"xmlns"==a.attributes[c].localName&&(f="");f in b||(b[f]=a.attributes[c].nodeValue)}a=a.parentNode}return b};
RDFaPredicate.prototype.toString=function(a){var b=null;a&&a.shorten&&a.graph?(b=a.graph.shorten(this.predicate,a.prefixesUsed))||(b="<"+this.predicate+">"):b="<"+this.predicate+">";for(var b=b+" ",c=0;c<this.objects.length;c++)if(0<c&&(b+=", "),"http://www.w3.org/1999/02/22-rdf-syntax-ns#object"==this.objects[c].type)"_:"==this.objects[c].value.substring(0,2)?b+=this.objects[c].value:a&&a.shorten&&a.graph?(b=a.graph.shorten(this.objects[c].value,a.prefixesUsed))||(b="<"+this.objects[c].value+">"):
b+="<"+this.objects[c].value+">";else if("http://www.w3.org/2001/XMLSchema#integer"==this.objects[c].type||"http://www.w3.org/2001/XMLSchema#decimal"==this.objects[c].type||"http://www.w3.org/2001/XMLSchema#double"==this.objects[c].type||"http://www.w3.org/2001/XMLSchema#boolean"==this.objects[c].type)b+=this.objects[c].value;else if("http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral"==this.objects[c].type){for(var f=new XMLSerializer,d="",i=0;i<this.objects[c].value.length;i++)if(this.objects[c].value[i].nodeType==
Node.ELEMENT_NODE){var j=RDFaPredicate.getPrefixMap(this.objects[c].value[i]),g=[],e;for(e in j)g.push(e);g.sort();for(var x=this.objects[c].value[i].cloneNode(!0),h=0;h<g.length;h++)x.setAttributeNS("http://www.w3.org/2000/xmlns/",0==g[h].length?"xmlns":"xmlns:"+g[h],j[g[h]]);d+=f.serializeToString(x)}else this.objects[c].value[i].nodeType==Node.TEXT_NODE&&(d+=this.objects[c].value[i].nodeValue);b+='"""'+d.replace(/"""/,'\\"\\"\\"')+'"""^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral>'}else f=
this.objects[c].value,b=0<=f.indexOf("\n")||0<=f.indexOf("\r")?b+('"""'+f.replace(/"""/,'\\"\\"\\"')+'"""'):b+('"'+f.replace(/"/,'\\"')+'"'),"http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral"!=this.objects[c].type?b+="^^<"+this.objects[c].type+">":this.objects[c].language&&(b+="@"+this.objects[c].language);return b};GraphRDFaProcessor.prototype=new RDFaProcessor;GraphRDFaProcessor.prototype.constructor=RDFaProcessor;function GraphRDFaProcessor(a){RDFaProcessor.call(this,a)}
GraphRDFaProcessor.prototype.getObjectSize=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};GraphRDFaProcessor.prototype.init=function(){this.target.tripleCount=0;var a=this;this.finishedHandlers.push(function(){for(var b in a.target.graph.subjects)0==a.getObjectSize(a.target.graph.subjects[b].predicates)&&delete a.target.graph.subjects[b]})};
GraphRDFaProcessor.prototype.newSubjectOrigin=function(a,b){for(var c=this.newSubject(null,b),f=0;f<c.origins.length;f++)if(c.origins[f]===a)return;c.origins.push(a);a.data||Object.defineProperty(a,"data",{value:c,writable:!1,configurable:!0,enumerable:!0})};GraphRDFaProcessor.prototype.newSubject=function(a,b){var c=this.target.graph.subjects[b];c||(c=new RDFaSubject(this.target,b),this.target.graph.subjects[b]=c);return c};
GraphRDFaProcessor.prototype.addTriple=function(a,b,c,f){var d=this.newSubject(a,b),b=d.predicates[c];b||(b=new RDFaPredicate(c),d.predicates[c]=b);for(var i=0;i<b.objects.length;i++)if(b.objects[i].type==f.type&&b.objects[i].value==f.value){b.objects[i].origin!==a&&(Array.isArray(b.objects[i].origin)||(c=[],c.push(b.objects[i].origin),b.objects[i].origin=c),b.objects[i].origin.push(a));return}this.target.tripleCount++;b.objects.push(f);f.origin=a;c==RDFaProcessor.typeURI&&d.types.push(f.value)};
GraphRDFaProcessor.rdfaCopyPredicate="http://www.w3.org/ns/rdfa#copy";GraphRDFaProcessor.rdfaPatternType="http://www.w3.org/ns/rdfa#Pattern";
GraphRDFaProcessor.prototype.copyProperties=function(){var a=[],b={},c;for(c in this.target.graph.subjects){var f=this.target.graph.subjects[c],d=f.predicates[GraphRDFaProcessor.rdfaCopyPredicate];if(d){a.push(c);for(var i=0;i<d.objects.length;i++)if(d.objects[i].type==RDFaProcessor.objectURI){var j=d.objects[i].value,g=this.target.graph.subjects[j];if(g){var e=g.predicates[RDFaProcessor.typeURI];if(e){for(var x=!1,h=0;h<e.objects.length&&!x;h++)e.objects[h].value==GraphRDFaProcessor.rdfaPatternType&&
e.objects[h].type==RDFaProcessor.objectURI&&(x=!0);if(x){b[j]=!0;for(var m in g.predicates)if(j=g.predicates[m],m==RDFaProcessor.typeURI){if(1!=j.objects.length)for(h=0;h<j.objects.length;h++)j.objects[h].value!=GraphRDFaProcessor.rdfaPatternType&&(e=f.predicates[m],e||(e=new RDFaPredicate(m),f.predicates[m]=e),e.objects.push({type:j.objects[h].type,value:j.objects[h].value,language:j.objects[h].language,origin:j.objects[h].origin}),f.types.push(j.objects[h].value))}else{e=f.predicates[m];e||(e=new RDFaPredicate(m),
f.predicates[m]=e);for(h=0;h<j.objects.length;h++)e.objects.push({type:j.objects[h].type,value:j.objects[h].value,language:j.objects[h].language,origin:j.objects[h].origin})}}}}}}}for(i=0;i<a.length;i++)f=this.target.graph.subjects[a[i]],delete f.predicates[GraphRDFaProcessor.rdfaCopyPredicate];for(c in b)delete this.target.graph.subjects[c]};
