package edu.rpi.tw.escience.waterquality;

import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Properties;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

import edu.rpi.tw.escience.waterquality.impl.ModuleManagerFactory;
import edu.rpi.tw.escience.waterquality.util.JavaScriptGenerator;
import edu.rpi.tw.escience.waterquality.util.SemantAquaConfiguration;

/**
 * The SemantAquaServlet class provides the main entry point to SemantAqua and is
 * primarily concerned with handling dynamic requests and performing the initial
 * configuration of the portal and its dependencies.
 * 
 * @author ewpatton
 *
 */
@WebServlet(name="SemantAqua",
			urlPatterns={"/rest/*","/js/modules/*","/js/config.js"},
			description="SemantAqua Portal",
			displayName="SemantAqua")
public class SemantAquaServlet extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5803626987887478846L;
	
	private Properties props = new Properties();
	
	private static final int HTTP_PORT = 80;
	private static final int HTTPS_PORT = 443;
	
	private Logger log = null;
	
	private static final int HTTP = 80;
	private static final int HTTPS = 443;
	
	private static final int HTTP = 80;
	private static final int HTTPS = 443;
	
	@Override
	public void init(ServletConfig config) throws ServletException {
		super.init(config);
		initLogger(config);
		log.info("Initializing SemantAqua");
		log.debug("Running on servlet version: "+getServletContext().getMajorVersion());
		log.debug("Servlet context path: "+getServletContext().getContextPath());
		SemantAquaConfiguration.configure(getServletContext());
		final String webinf = config.getServletContext().getRealPath("WEB-INF");
		log.debug("WEB-INF: "+webinf);
		File modules = new File(webinf+"/modules");
		if(!modules.exists()) {
			log.info("Creating modules directory");
			modules.mkdir();
		}
		ModuleManagerFactory.getInstance().setModulePath(modules.getAbsolutePath());
		log.info("Finished initializing SemantAqua");
	}
	
	private void initLogger(ServletConfig config) {
		String log4jconfig = config.getInitParameter("log4j-properties-location");
		ServletContext context = config.getServletContext();
		if(log4jconfig == null) {
			BasicConfigurator.configure();
		}
		else {
			String appPath = context.getRealPath("/");
			String log4jpath = appPath + log4jconfig;
			if(new File(log4jpath).exists()) {
				PropertyConfigurator.configure(log4jpath);
				log = Logger.getLogger(SemantAquaServlet.class);
			}
			else {
				BasicConfigurator.configure();
			}
		}
	}

	@Override
	public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
		log.debug(request.getScheme());
		log.debug(request.getServerName());
		log.debug(""+request.getServerPort());
		log.debug(request.getContextPath());
		log.debug(request.getServletPath());
		log.debug(request.getPathInfo());
		log.debug(request.getRequestURI());
		PrintStream ps = null;
		if(request.getServletPath().equals("/js/config.js")) {
			printConfig(request, response);
		}
		else if(request.getServletPath().equals("/js/modules")) {
			printAjax(request, response);
		}
		else {
			ps = new PrintStream(response.getOutputStream());
			ps.println("<h1>It works!</h1>");
			ps.close();
		}
	}
	
	@Override
	public String getServletInfo() {
		getServletContext().getResourceAsStream("/META-INF/maven/edu.rpi.tw.escience/semantauqa/pom.properties");
		return "SemantAqua";
	}
	
	@Override
	public long getLastModified(HttpServletRequest request) {
		return -1;
	}
	
	private void printConfig(HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setHeader("Content-Type", "text/javascript");
		PrintStream ps = new PrintStream(response.getOutputStream());
		String baseUrl = computeBaseUrl(request);
		if(SemantAquaConfiguration.get().isDebug()) {
			ps.println("// file autogenerated by "+getClass().getName()+"#printConfig");
		}
		ps.println("var SemantAqua = { \"baseUrl\": \""+baseUrl+"\", \"restBaseUrl\": \""+baseUrl+"rest/\" }");
		ps.close();
	}
	
	private void printAjax(HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setHeader("Content-Type", "text/javascript");
		PrintStream ps = new PrintStream(response.getOutputStream());
		String module = request.getPathInfo().replace("/", "").replace(".js", "");
		ModuleManager mgr = ModuleManagerFactory.getInstance().getManager();
		Module mod = mgr.getModuleByName(module);
		if(mod != null) {
			ps.println(JavaScriptGenerator.ajaxForModule(mod));
		}
		ps.close();
	}
	
	private String computeBaseUrl(HttpServletRequest request) {
		if(props.contains("baseUrl") && !props.get("baseUrl").equals("")) {
			return props.getProperty("baseUrl");
		}
		else {
			String path = "";
			path += request.getScheme();
			path += "://";
			path += request.getServerName();
			if(request.getScheme().equals("http") && request.getServerPort() != HTTP) {
				path += ":"+request.getServerPort();
			}
			else if(request.getScheme().equals("https") && request.getServerPort() != HTTPS) {
				path += ":"+request.getServerPort();
			}
			path += request.getContextPath();
			path += "/";
			return path;
		}
	}
	
	/**
	 * Returns whether or not the servlet is built in a debug profile
	 * @return
	 */
	public static boolean isDebug() {
		return debugging;
	}

}
