package edu.rpi.tw.escience.semanteco.taglib.core;

import java.io.IOException;

import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspWriter;
import javax.servlet.jsp.tagext.TagSupport;

import org.apache.log4j.Logger;

/**
 * The ScriptTag class provides a means for SemantEco JSP to provide JavaScript
 * from the various modules as well as the autogenerated JavaScript provided
 * for executing QueryMethod annotated queries on the server via a RESTful call.
 * 
 * @author ewpatton
 *
 */
public class ScriptTag extends TagSupport {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7903606798820268678L;
	private final transient Logger log = Logger.getLogger(ScriptTag.class);
	
	/**
	 * Default constructor used by the JSP processor to instantiate this class
	 */
	public ScriptTag() {
		
	}

	protected void writeScript(JspWriter out, String url) throws IOException {
		out.write("<script src=\"");
		out.write(url);
		out.write("\" type=\"text/javascript\"></script>\r\n");
	}

	@Override
	public int doStartTag() throws JspException {
		log.debug("Generating <script> entries");
		final JspWriter out = pageContext.getOut();
		try {
			writeScript(out, "js/underscore-min.js");
			writeScript(out, "js/jquery-1.7.1.min.js");
			writeScript(out, "js/jquery-ui-1.10.1.custom.min.js");
			writeScript(out, "js/jquery.ba-bbq-1.2.1.js");
			writeScript(out, "js/jquery.cookie.js");
			writeScript(out, "js/jquery.client.js");
			writeScript(out, "js/jquery.scrollfollow.js");
			writeScript(out, "js/modernizr-2.0.js");
			writeScript(out, "js/d3.js");
			writeScript(out, "js/d3.csv.js");
			writeScript(out, "js/d3.time.js");
			writeScript(out, "js/json.js");
			writeScript(out, "js/URI.min.js");
			writeScript(out, "js/SemantEco.js");
			writeScript(out, "js/SemantEcoUI.js");
			writeScript(out, "js/SemantEcoUI.HierarchicalFacet.js");
			writeScript(out, "js/config.js");
			writeScript(out, "js/jqplot/jquery.jqplot.min.js");
			writeScript(out, "js/jqplot/plugins/jqplot.highlighter.js");
			writeScript(out, "js/jqplot/plugins/jqplot.cursor.min.js");
			writeScript(out, "js/jqplot/plugins/jqplot.dateAxisRenderer.min.js");
			writeScript(out, "js/jstree/jquery.jstree.js");
			writeScript(out, "js/ui.dropdownchecklist.js");
		}
		catch(IOException e) {
			log.error("Unable to generate list of scripts", e);
		}
		return SKIP_BODY;
	}

}
