PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT *
WHERE 
{
graph <http://sparql.tw.rpi.edu/semanteco/data-source> {
?graph <http://rdfs.org/sioc/ns#topic> <http://logd.tw.rpi.edu/id/us/state/Rhode_Island> . 
?graph <http://purl.org/dc/terms/source> <http://sparql.tw.rpi.edu/source/usgs-gov> . 
}
}
