PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT 
?s 
WHERE 
{
graph <http://sparql.tw.rpi.edu/source/usgs-gov/dataset/nwis-sites-ri/version/2011-Mar-20> {
?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://escience.rpi.edu/ontology/semanteco/2/0/water.owl#WaterSite> . 
?s <http://escience.rpi.edu/ontology/semanteco/2/0/pollution.owl#hasCountyCode> "7"^^xsd:int . 
?s <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?lat . 
?s <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?long . 
}
graph <http://sparql.tw.rpi.edu/source/usgs-gov/dataset/nwis-measurements-ri/version/2011-Mar-20> {
?measurement <http://escience.rpi.edu/ontology/semanteco/2/0/pollution.owl#hasSite> ?s . 
}
}
ORDER BY ASC(((?lat - 41.74936)*(?lat - 41.74936)+(?long - -71.40836)*(?long - -71.40836)))
OFFSET 0
LIMIT 10
